#!/bin/bash

if [ ! -f ~/.redisrc ]
then
	echo "Redis list not found in ~/.redisrc"
	exit 1
fi

if [ $# -eq 0 ]
then
	echo "Usage: $0 <redis cmd>"
	exit
fi

CMD=$@
echo $CMD

for s in `cat ~/.redisrc`
do
	echo -n "$s	"
	host=$(echo $s | cut -d':' -f1)
	port=$(echo $s | cut -d':' -f2)

	redis-cli -h $host -p $port $CMD
done
